app/main/routes.py
# uncompyle6 version 3.2.3
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
# [GCC 7.3.0]
# Embedded file name: /run/user/1000/gvfs/smb-share:server=dibro-elite.local,share=pycharmprojects/lesho-construction/app/main/routes.py
# Compiled at: 2018-09-11 17:46:42
from datetime import datetime
from flask import render_template, flash, redirect, abort, url_for, request, g, jsonify, current_app
from flask_login import current_user, login_required
from flask_uploads import UploadSet, configure_uploads, IMAGES
from app import db
from flask import Blueprint
from app.models import *
from app.main.forms import *
from xkcdpass import xkcd_password as xp
import os, random, string
from app.auth.email import send_user_added_email
main = Blueprint('main', __name__)
photos = UploadSet('photos', IMAGES)


@main.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
        g.search_form = SearchForm()
    g.company = Company.query.first()
    g.images = Theme.query.first()
    now = datetime.utcnow()
    if(now.day == 5):
        tenants=Tenant.query.all()
        updated_at=tenants[0].rent_updated_at
        if updated_at.month != now.month:
            for tenant in tenants:
                tenant.rent_due=(float(tenant.house.property_price) + tenant.rent_due)
                tenant.rent_updated_at=datetime.utcnow()
            db.session.commit()
    county=County.query.first()
    if county is None:
        file_name = 'conties.csv'
        data = County.Load_Data(file_name)
        for i in data:
            record = County(**{
                'SNo' : i[0],
                'county' : i[1]
            })
            db.session.add(record)
        db.session.commit()



@main.route('/', methods=['GET', 'POST'])
@main.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    property_count = Property.query.filter_by(author=current_user).count()
    if current_user.role.role == 'admin':
        property_count = Property.query.count()
    tenant=None
    if current_user.role.role == 'tenant':
        tenant = Tenant.query.filter_by(email=current_user.email).first_or_404()
    labour_count = Labour.query.count()
    equipment_count = Equipment.query.count()
    consultancy_count = Consultancy.query.count()
    count_all = {'property': property_count, 'labour': labour_count, 'equipment': equipment_count,
                 'consultancy': consultancy_count,'tenant':tenant}
    labour = Labour.query.limit(5)
    consultancy = Consultancy.query.limit(5)
    property = Property.query.filter_by(author=current_user).limit(5)
    if current_user.role.role == 'admin':
        property = Property.query.limit(5)
    equipment = Equipment.query.limit(5)
    tables = {'labour': labour, 'consultancy': consultancy, 'property': property, 'equipment': equipment}
    return render_template('admin/index.html', count_all=count_all, tables=tables)


@main.route('/users', methods=['GET', 'POST'])
@login_required
def users():
    if current_user.role.access_user != True:
        flash("You don't have access to this module!", 'danger')
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    form.role.choices = [(row.id, row.role) for row in Role.query.order_by(Role.created_at.desc()).all()]
    if form.validate_on_submit():
        role = Role.query.filter_by(id=form.role.data).first_or_404()
        user = User(username=form.username.data, phone_number=form.phone_number.data, role=role, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('User added successfully!', 'success')
        return redirect(url_for('main.users'))
    users = User.query.order_by(User.last_seen.desc()).all()
    return render_template('admin/users.html', form=form, users=users)


@main.route('/edit_user/<id>', methods=['GET', 'POST'])
@login_required
def edit_user(id):
    if current_user.role.permissions.write_user != True:
        flash("You don't have access to this module!", 'danger')
        return redirect(url_for('main.index'))
    user = User.query.filter_by(id=id).first_or_404()
    form = EditRegistrationForm(obj=user)
    form.role.choices = [(row.id, row.role) for row in Role.query.order_by(Role.created_at.desc()).all()]
    if form.validate_on_submit():
        role = Role.query.filter_by(id=form.role.data).first_or_404()
        user.username = form.username.data
        user.role = role
        user.phone_number = form.phone_number.data
        db.session.commit()
        flash('User edited successfully', 'success')
        return redirect(url_for('main.users'))
    return render_template('admin/edit_user.html', form=form, title='Edit User')


@main.route('/add_role', methods=['GET', 'POST'])
@login_required
def add_role():
    if request.method == 'POST':
        role = Role(role=request.form['role'])
        permission = Permission(role=role)
        db.session.add(role)
        db.session.commit()
    return jsonify({'status': 1})

#edit role
@main.route('/edit_role/<id>', methods=['GET', 'POST'])
@login_required
def edit_role(id):
    role = Role.query.filter_by(id=id).first_or_404()
    if request.method == 'POST':
        role.role = request.form['role']
        db.session.commit()
        return jsonify({'status': 1})
    elif request.method == 'GET':
        data={'role':role.role, 'id':role.id}
        return jsonify({'status': 1, 'data':data})


@main.route('/view_user/<id>')
@login_required
def view_user(id):
    if current_user.role.permissions.read_user != True:
        flash("You don't have access to this module!", 'danger')
        return redirect(url_for('main.index'))
    user = User.query.filter_by(id=id).first_or_404()
    return render_template('admin/view_user.html', title='view user', user=user)


@main.route('/role_permissions', methods=['GET', 'POST'])
@login_required
def role_permissions():
    if current_user.role.permissions.read_user != True:
        flash("You don't have access to this module!", 'danger')
        return redirect(url_for('main.index'))
    roles = Role.query.order_by(Role.created_at.desc()).all()
    return render_template('admin/role_permissions.html', roles=roles, title='Roles & Permission')


@main.route('/role_permissions_values', methods=['GET', 'POST'])
@login_required
def role_permissions_values():
    role = Role.query.order_by(Role.created_at.desc()).first()
    if role is None:
        return jsonify({'status': 0})
    if request.method == 'POST':
        role = Role.query.filter_by(id=request.form['id']).first_or_404()
    response = jsonify({'status': 1, 'data': role.to_dict_role()})
    return response


@main.route('/edit_role_permissions_js', methods=['GET', 'POST'])
@login_required
def edit_role_permissions_js():
    role = Role.query.filter_by(id=request.form['id']).first_or_404()
    data = request.form
    role.from_dict(data)
    role.permissions.from_dict_permissions(data)
    db.session.commit()
    return jsonify({'status': 1})


@main.route('/company_settings', methods=['GET', 'POST'])
@login_required
def company_settings():
    if current_user.role.permissions.read_user != True:
        flash("You don't have access to this module!", 'danger')
        return redirect(url_for('main.index'))
    company = Company.query.first()
    if company is None:
        form = CompanyForm()
        if form.validate_on_submit():
            company = Company(company_name=form.company_name.data, contact_person=form.contact_person.data,
                              phone_number=form.phone_number.data, email=form.email.data, address=form.address.data,
                              country=form.country.data, city=form.city.data, state=form.state.data,
                              postal_code=form.postal_code.data, bank_name=form.bank_name.data,
                              bank_country=form.bank_country.data, bank_address=form.bank_address.data,
                              account_number=form.account_number.data)
            db.session.add(company)
            db.session.commit()
            flash('company settings updated successfully', 'success')
            return redirect(url_for('main.company_settings'))
    else:
        form = CompanyForm(obj=company)
        if form.validate_on_submit():
            form.populate_obj(company)
            db.session.commit()
            flash('company settings updated successfully', 'success')
            return redirect(url_for('main.company_settings'))
    return render_template('admin/company_settings.html', form=form, title='Company Settings')


@main.route('/theme_settings', methods=['GET', 'POST'])
@login_required
def theme_settings():
    if current_user.role.permissions.read_user != True:
        flash("You don't have access to this module!", 'danger')
        return redirect(url_for('main.index'))
    theme = Theme.query.first()
    if theme is None:
        form = ThemeForm()
        if form.validate_on_submit():
            photos = UploadSet('photos', IMAGES)
            logo = photos.save(form.logo.data)
            favicon = photos.save(form.favicon.data)
            theme = Theme(company_name=form.company_name.data, logo=logo, favicon=favicon)
            db.session.add(theme)
            db.session.commit()
            flash('theme settings updated successfully', 'success')
            return redirect(url_for('main.theme_settings'))
    else:
        form = ThemeForm(obj=theme)
        if form.validate_on_submit():
            photos = UploadSet('photos', IMAGES)
            logo = photos.save(form.logo.data)
            favicon = photos.save(form.favicon.data)
            theme.company_name = form.company_name.data
            theme.logo = logo
            theme.favicon = favicon
            db.session.commit()

app/templates/includes/header-navigation.html
<div class="header">
    <div class="header-left">
        <a href="{{url_for('main.index')}}" class="logo">
<img src="{% if g.images %}{{url_for('static', filename='uploads/{}'.format(g.images.logo))}}{% else %}{{url_for('static',filename='img/logo.png')}}{% endif %}" width="40" height="40" alt="">
</a>
    </div>
    <div class="page-title-box pull-left">
<h3>{% if g.company %}{{ g.company.company_name }}{% else %}Skye Technologies{% endif %}</h3>
    </div>
<a id="mobile_btn" class="mobile_btn pull-left" href="#sidebar"><i class="fa fa-bars" aria-hidden="true"></i></a>
<ul class="nav navbar-nav navbar-right user-menu pull-right">
<li class="dropdown">
<a href="#" class="dropdown-toggle user-link" data-toggle="dropdown" title="{{ current_user.role.role }}">
  <span class="user-img"><img class="img-circle" src="{{url_for('static', filename='img/user.jpg')}}" width="40" alt="{{ current_user.username }}">
  <span class="status online"></span></span>
  <span>{{ current_user.username }}</span>
  <i class="caret"></i>
</a>
<ul class="dropdown-menu">
  <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
</ul>
</li>
</ul>
<div class="dropdown mobile-user-menu pull-right">
<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
<ul class="dropdown-menu pull-right">
<li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
</ul>
</div>
</div>

app/templates/includes/sidebar-navigation.html
<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                <li {%- if request.path== url_for(
                'main.index') %} class="active"{% endif %} >
                <a href="{{ url_for('main.index') }}">Dashboard</a>
                </li>
                {% if current_user.role.access_property == True %}
                <li class="submenu">
                    <a href="#"><span> Property management</span> <span class="menu-arrow"></span></a>
                    <ul class="list-unstyled" style="display: none;">
                        {% if current_user.role.permissions.create_property == True %}
                        <li><a {%- if request.path== url_for('main.add_property_type') %} class="active"{% endif %}
                            href="{{ url_for('main.add_property_type') }}">Add property type</a></li>
                            {% endif %}
                            {% if current_user.role.permissions.read_property == True %}
                            <li><a {%- if request.path== url_for('main.view_property_type') %} class="active"{% endif %} href="{{
                            url_for('main.view_property_type') }}">View Property Type</a></li>
                            {% endif %}
                            {% if current_user.role.permissions.read_property == True %}
                            <li><a {%- if request.path== url_for('main.tenants') %} class="active"{% endif %} href="{{
                            url_for('main.tenants') }}">Tenants</a></li>
                            {% endif %}
                            <li><a {%- if request.path== url_for('main.payments') %} class="active"{% endif %} href="{{
                            url_for('main.payments') }}">Payments</a></li>
                    </ul>
                </li>
                {% endif %}
                {% if current_user.role.access_labour == True %}
                <li class="submenu">
                    <a href="#"><span> Labour</span> <span class="menu-arrow"></span></a>
                    <ul class="list-unstyled" style="display: none;">
                      {% if current_user.role.permissions.create_labour == True %}
                        <li><a {%- if request.path== url_for('main.add_labour_type') %} class="active"{% endif %}
                            href="{{ url_for('main.add_labour_type') }}">Add labour type</a></li>
                            {% endif %}
                            {% if current_user.role.permissions.read_labour == True %}
                        <li><a {%- if request.path== url_for('main.view_labour_type') %} class="active"{% endif %} href="{{
                            url_for('main.view_labour_type') }}">View Labour Type</a></li>
                            {% endif %}
                    </ul>
                </li>
                {% endif %}
                {% if current_user.role.access_equipment %}
                <li class="submenu">
                    <a href="#"><span> Equipment</span> <span class="menu-arrow"></span></a>
                    <ul class="list-unstyled" style="display: none;">
                      {% if current_user.role.permissions.create_equipment == True %}
                        <li><a {%- if request.path== url_for('main.add_equipment_type') %} class="active"{% endif %}
                            href="{{ url_for('main.add_equipment_type') }}">Add equipment type</a></li>
                        {% endif %}
                        {% if current_user.role.permissions.read_equipment == True %}
                        <li><a {%- if request.path== url_for('main.view_equipment_type') %} class="active"{% endif %} href="{{
                            url_for('main.view_equipment_type') }}">View Equipment Type</a></li>
                            {% endif %}
                    </ul>
                </li>
                {% endif %}
                {% if current_user.role.access_construction %}
                <li class="submenu">
                    <a href="#"><span> Constructon Materials</span> <span class="menu-arrow"></span></a>
                    <ul class="list-unstyled" style="display: none;">
                      {% if current_user.role.permissions.create_construction == True %}
                        <li><a {%- if request.path== url_for('main.add_construction_materials_type') %} class="active"{%
                            endif %} href="{{ url_for('main.add_construction_materials_type') }}">Add construction
                            type</a></li>
                            {% endif %}
                            {% if current_user.role.permissions.read_construction == True %}
                        <li><a {%- if request.path== url_for('main.view_construction_materials_type') %} class="active"{% endif %}
                            href="{{ url_for('main.view_construction_materials_type') }}">Construction materials type</a></li>
                            {% endif %}
                    </ul>
                </li>
                {% endif %}
                {% if current_user.role.access_consultancy %}
                <li class="submenu">
                    <a href="#"><span> Consultancy Services</span> <span class="menu-arrow"></span></a>
                    <ul class="list-unstyled" style="display: none;">
                      {% if current_user.role.permissions.create_consultancy == True %}
                        <li><a {%- if request.path== url_for('main.add_consultancy_services_type') %} class="active"{%
                            endif %} href="{{ url_for('main.add_consultancy_services_type') }}">Add consultancy type</a>
                        </li>
                        {% endif %}
                        {% if current_user.role.permissions.read_consultancy == True %}
                        <li><a {%- if request.path== url_for('main.view_consultancy_services_type') %} class="active"{% endif %}
                            href="{{ url_for('main.view_consultancy_services_type') }}">View consultancy type</a></li>
                            {% endif %}
                    </ul>
                </li>
                {% endif %}
                {% if current_user.role.access_house_design %}
                <li class="submenu">
                    <a href="#"><span> Latest House Designs</span> <span class="menu-arrow"></span></a>
                    <ul class="list-unstyled" style="display: none;">
                      {% if current_user.role.permissions.create_house_design == True %}
                        <li><a {%- if request.path== url_for('main.add_latest_house_designs_type') %} class="active"{%
                            endif %} href="{{ url_for('main.add_latest_house_designs_type') }}">Add designs type</a>
                        </li>
                        {% endif %}
                        {% if current_user.role.permissions.read_house_design == True %}
                        <li><a {%- if request.path== url_for('main.view_latest_house_designs_type') %} class="active"{% endif %}
                            href="{{ url_for('main.view_latest_house_designs_type') }}">View Designs type</a></li>
                        {% endif %}
                    </ul>
                </li>
                {% endif %}
                {% if current_user.role.access_financing == True %}
                <li {%- if request.path== url_for(
                'main.financing') %} class="active"{% endif %} >
                <a href="{{ url_for('main.financing') }}">Financing</a>
                </li>
                {% endif %}
                {% if current_user.role.access_projects == True %}
                <li {%- if request.path== url_for(
                'main.projects') %} class="active"{% endif %} >
                <a href="{{ url_for('main.projects') }}">Projects</a>
                </li>
                {% endif %}
                <li {%- if request.path == url_for('main.settings')  %} class="active"{% endif %}>
                <a href="{{ url_for('main.settings') }}">Settings</a>
              </li>
                {% if current_user.role.access_user == True %}
              <li class="submenu">
                  <a href="#"><span> Admin </span> <span class="menu-arrow"></span></a>
                  <ul class="list-unstyled" style="display: none;">
                    <li><a {%- if request.path ==  url_for('main.users') %} class="active"{% endif %} href="{{ url_for('main.users') }}">Users</a></li>
                    {% if current_user.role.permissions.read_user == True %}
                    <li><a {%- if request.path ==  url_for('main.role_permissions') %} class="active"{% endif %} href="{{ url_for('main.role_permissions') }}">Role & Permission </a></li>
                    {% endif %}
                    {% if current_user.role.permissions.read_user == True %}
                    <li><a {%- if request.path ==  url_for('main.company_settings') %} class="active"{% endif %} href="{{ url_for('main.company_settings') }}">Company settings </a></li>
                    {% endif %}
                    {% if current_user.role.permissions.read_user == True %}
                    <li><a {%- if request.path ==  url_for('main.theme_settings') %} class="active"{% endif %} href="{{ url_for('main.theme_settings') }}">Theme settings </a></li>
                    {% endif %}
                  </ul>
              </li>
              {% endif %}
            </ul>
        </div>
    </div>
</div>